/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import logica.*;

/**
 *
 * @author rodrigo
 */
public class Pantalla_opciones extends javax.swing.JFrame {

    int n_dia = Principal.estado_dia;
    public int modo_a = 1;

    Reproducirm reproductor = Reproducirm.obinstancia();
    Modificarmodos modos = Modificarmodos.obinstancia();
    Jugador jugador = Jugador.datos_jugador("Rodrigo");

    /**
     * Creates new form Pantalla_opciones
     */
    public Pantalla_opciones() {
        initComponents();
        if (Principal.modo_oscuro) {
            I_opciones.setVisible(false);
            I_opcionesoscuro.setVisible(true);
        } else {
            I_opciones.setVisible(true);
            I_opcionesoscuro.setVisible(false);
        }

        control_cambioU();
    }

    public void control_cambioU() {
        nomUsuario.setBackground(new java.awt.Color(0, 0, 0, 1));
        nomUsuario.setVisible(false);
        bannernombre.setVisible(false);
        btnGuardar.setVisible(false);
        instrucciones.setVisible(false);
        cerrarinfo.setVisible(false);
        acercajuego.setVisible(false);
        btncerraraj.setVisible(false);
        BotonModo1.setVisible(false);
        nombreJL.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreJL = new javax.swing.JLabel();
        nombreJ = new javax.swing.JButton();
        btncerraraj = new javax.swing.JButton();
        acercajuego = new javax.swing.JLabel();
        cerrarinfo = new javax.swing.JButton();
        instrucciones = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        nomUsuario = new javax.swing.JTextField();
        bannernombre = new javax.swing.JLabel();
        btn_retroceso = new javax.swing.JButton();
        BotonModo1 = new javax.swing.JButton();
        BotonModo = new javax.swing.JButton();
        BotonSonido = new javax.swing.JButton();
        Acercade = new javax.swing.JButton();
        InstruccionesJuego = new javax.swing.JButton();
        Nombre_Jugador = new javax.swing.JButton();
        I_opcionesoscuro = new javax.swing.JLabel();
        I_opciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(nombreJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 160, 100));

        nombreJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreJMouseClicked(evt);
            }
        });
        nombreJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreJActionPerformed(evt);
            }
        });
        getContentPane().add(nombreJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 50, 50));

        btncerraraj.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/btnretroceso.png")); // NOI18N
        btncerraraj.setBorderPainted(false);
        btncerraraj.setContentAreaFilled(false);
        btncerraraj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrarajMouseClicked(evt);
            }
        });
        getContentPane().add(btncerraraj, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 40, 40));

        acercajuego.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/info_juego.png")); // NOI18N
        getContentPane().add(acercajuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 250, 100));

        cerrarinfo.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/btnretroceso.png")); // NOI18N
        cerrarinfo.setBorderPainted(false);
        cerrarinfo.setContentAreaFilled(false);
        cerrarinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarinfoMouseClicked(evt);
            }
        });
        getContentPane().add(cerrarinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 40, 40));

        instrucciones.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/acerrca.png")); // NOI18N
        getContentPane().add(instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 710));

        btnGuardar.setBackground(new java.awt.Color(139, 165, 194));
        btnGuardar.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/btnguardar.png")); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 90, 30));

        nomUsuario.setBackground(new java.awt.Color(242, 192, 123));
        nomUsuario.setFont(new java.awt.Font("Classic Console", 0, 18)); // NOI18N
        nomUsuario.setForeground(new java.awt.Color(255, 255, 255));
        nomUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomUsuario.setBorder(null);
        nomUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(nomUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 150, 40));

        bannernombre.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/bannernombre.png")); // NOI18N
        bannernombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bannernombreMouseClicked(evt);
            }
        });
        getContentPane().add(bannernombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 240, 80));

        btn_retroceso.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/btnretroceso.png")); // NOI18N
        btn_retroceso.setBorderPainted(false);
        btn_retroceso.setContentAreaFilled(false);
        btn_retroceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_retrocesoMouseClicked(evt);
            }
        });
        getContentPane().add(btn_retroceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 40, 40));

        BotonModo1.setToolTipText("");
        BotonModo1.setBorderPainted(false);
        BotonModo1.setContentAreaFilled(false);
        BotonModo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonModo1MouseClicked(evt);
            }
        });
        getContentPane().add(BotonModo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 50, 50));

        BotonModo.setToolTipText("");
        BotonModo.setBorderPainted(false);
        BotonModo.setContentAreaFilled(false);
        BotonModo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonModoMouseClicked(evt);
            }
        });
        getContentPane().add(BotonModo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 50, 50));

        BotonSonido.setToolTipText("");
        BotonSonido.setBorderPainted(false);
        BotonSonido.setContentAreaFilled(false);
        BotonSonido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSonidoMouseClicked(evt);
            }
        });
        getContentPane().add(BotonSonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 380, 80, 50));

        Acercade.setToolTipText("");
        Acercade.setBorderPainted(false);
        Acercade.setContentAreaFilled(false);
        Acercade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcercadeMouseClicked(evt);
            }
        });
        getContentPane().add(Acercade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 140, 30));

        InstruccionesJuego.setToolTipText("");
        InstruccionesJuego.setBorderPainted(false);
        InstruccionesJuego.setContentAreaFilled(false);
        InstruccionesJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InstruccionesJuegoMouseClicked(evt);
            }
        });
        getContentPane().add(InstruccionesJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 140, 30));

        Nombre_Jugador.setToolTipText("");
        Nombre_Jugador.setBorderPainted(false);
        Nombre_Jugador.setContentAreaFilled(false);
        Nombre_Jugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Nombre_JugadorMouseClicked(evt);
            }
        });
        getContentPane().add(Nombre_Jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, 30));

        I_opcionesoscuro.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/opcionesocuro.png")); // NOI18N
        getContentPane().add(I_opcionesoscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 710));

        I_opciones.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/Opciones.png")); // NOI18N
        I_opciones.setLabelFor(I_opciones);
        getContentPane().add(I_opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 401, 711));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_retrocesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_retrocesoMouseClicked
        Pantalla_incio PIN = new Pantalla_incio();
        PIN.setVisible(true);
        PIN.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_retrocesoMouseClicked

    private void Nombre_JugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Nombre_JugadorMouseClicked
        bannernombre.setVisible(true);
        nomUsuario.setOpaque(false);
        nomUsuario.setVisible(true);
        btnGuardar.setVisible(true);
    }//GEN-LAST:event_Nombre_JugadorMouseClicked

    private void bannernombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bannernombreMouseClicked

    }//GEN-LAST:event_bannernombreMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        String nuevo_nombre = nomUsuario.getText();
        jugador.cambiar_nombre(nuevo_nombre);
        bannernombre.setVisible(false);
        nomUsuario.setOpaque(true);
        nomUsuario.setVisible(false);
        btnGuardar.setVisible(false);

        System.out.println(jugador.nombre);
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void InstruccionesJuegoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InstruccionesJuegoMouseClicked
        instrucciones.setVisible(true);
        cerrarinfo.setVisible(true);
    }//GEN-LAST:event_InstruccionesJuegoMouseClicked

    private void cerrarinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarinfoMouseClicked
        instrucciones.setVisible(false);
        cerrarinfo.setVisible(false);
    }//GEN-LAST:event_cerrarinfoMouseClicked

    private void nomUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomUsuarioActionPerformed

    private void BotonModoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonModoMouseClicked
        boolean modo;
        if (modos.m_actual == 1) {
            modo = false;
            modos.actualizar_modo(modo);
            System.out.println("Se envia modo oscuro");
            modos.m_actual = 2;
        } else {
            modo = true;
            modos.actualizar_modo(modo);
            System.out.println("Se envia modo 2");
            modos.m_actual = 1;
        }

    }//GEN-LAST:event_BotonModoMouseClicked

    private void AcercadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcercadeMouseClicked
        acercajuego.setVisible(true);
        btncerraraj.setVisible(true);
    }//GEN-LAST:event_AcercadeMouseClicked

    private void btncerrarajMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarajMouseClicked
        acercajuego.setVisible(false);
        btncerraraj.setVisible(false);
    }//GEN-LAST:event_btncerrarajMouseClicked

    private void BotonModo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonModo1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonModo1MouseClicked

    private void BotonSonidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSonidoMouseClicked

        reproductor.hacerloop(true);
        if (!reproductor.rpmusica()) {
            reproductor.reproducir();
        } else {
            reproductor.detener();
        }
    }//GEN-LAST:event_BotonSonidoMouseClicked

    private void nombreJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreJActionPerformed

    private void nombreJMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreJMouseClicked
        String nm;
        int punt;
        punt = jugador.puntuacion;
        nm = jugador.nombre;
        
        nombreJL.setVisible(true);
        nombreJL.setText(nm + " con una puntuacion de: " + punt);
    }//GEN-LAST:event_nombreJMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acercade;
    private javax.swing.JButton BotonModo;
    public javax.swing.JButton BotonModo1;
    private javax.swing.JButton BotonSonido;
    public static javax.swing.JLabel I_opciones;
    public static javax.swing.JLabel I_opcionesoscuro;
    private javax.swing.JButton InstruccionesJuego;
    private javax.swing.JButton Nombre_Jugador;
    private javax.swing.JLabel acercajuego;
    private javax.swing.JLabel bannernombre;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btn_retroceso;
    private javax.swing.JButton btncerraraj;
    private javax.swing.JButton cerrarinfo;
    public javax.swing.JLabel instrucciones;
    private javax.swing.JTextField nomUsuario;
    private javax.swing.JButton nombreJ;
    private javax.swing.JLabel nombreJL;
    // End of variables declaration//GEN-END:variables
}
