/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import logica.Principal;

/**
 *
 * @author rodrigo
 */
public class Pantalla_incio extends javax.swing.JFrame{

    /**
     * Creates new form Pantalla_incio
     */
    public Pantalla_incio() {
        initComponents();
        if (Principal.modo_oscuro) {
            I_iniciooscuro.setVisible(true);
            I_Inicio.setVisible(false);
        } else {
            I_iniciooscuro.setVisible(false);
            I_Inicio.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton_salir = new javax.swing.JButton();
        Boton_opciones = new javax.swing.JButton();
        Boton_inicio = new javax.swing.JButton();
        I_Inicio = new javax.swing.JLabel();
        I_iniciooscuro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Boton_salir.setBorderPainted(false);
        Boton_salir.setContentAreaFilled(false);
        Boton_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_salirMouseClicked(evt);
            }
        });
        Boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_salirActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 140, 30));

        Boton_opciones.setBorderPainted(false);
        Boton_opciones.setContentAreaFilled(false);
        Boton_opciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_opcionesMouseClicked(evt);
            }
        });
        Boton_opciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_opcionesActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 140, 30));

        Boton_inicio.setBorderPainted(false);
        Boton_inicio.setContentAreaFilled(false);
        Boton_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Boton_inicioMouseClicked(evt);
            }
        });
        Boton_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_inicioActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 140, 30));

        I_Inicio.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/Pantalla_inicio1.png")); // NOI18N
        I_Inicio.setText("jLabel1");
        getContentPane().add(I_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 401, 706));

        I_iniciooscuro.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/iniciooscuro.png")); // NOI18N
        I_iniciooscuro.setText("jLabel1");
        getContentPane().add(I_iniciooscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_inicioActionPerformed
        
    }//GEN-LAST:event_Boton_inicioActionPerformed

    private void Boton_opcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_opcionesActionPerformed
        
    }//GEN-LAST:event_Boton_opcionesActionPerformed

    private void Boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_salirActionPerformed
        
    }//GEN-LAST:event_Boton_salirActionPerformed

    private void Boton_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_inicioMouseClicked
        Pantalla_modos pm = new Pantalla_modos();
        pm.setVisible(true);
        pm.setLocationRelativeTo(null);
        Pantalla_incio.this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_inicioMouseClicked

    private void Boton_opcionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_opcionesMouseClicked
        Pantalla_opciones po = new Pantalla_opciones();
        po.setVisible(true);
        po.setLocationRelativeTo(null);
        Pantalla_incio.this.dispose();
    }//GEN-LAST:event_Boton_opcionesMouseClicked

    private void Boton_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton_salirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Boton_salirMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_inicio;
    private javax.swing.JButton Boton_opciones;
    private javax.swing.JButton Boton_salir;
    public javax.swing.JLabel I_Inicio;
    private javax.swing.JLabel I_iniciooscuro;
    // End of variables declaration//GEN-END:variables
}
