package interfaz;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rodrigo
 */
import logica.*;
import interfaz.Pantalla_juegoP;

public class Pantalla_modos extends javax.swing.JFrame {
    public int opcion = 1;
    /**
     * Creates new form Pantalla_modos
     */
    public Pantalla_modos() {
        initComponents();
        if (Principal.modo_oscuro) {
            I_modososcuro.setVisible(true);
            I_modos.setVisible(false);
        } else {
            I_modososcuro.setVisible(false);
            I_modos.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_retroceso = new javax.swing.JButton();
        Modo_dificil = new javax.swing.JButton();
        Modo_facil = new javax.swing.JButton();
        Modo_medio = new javax.swing.JButton();
        I_modos = new javax.swing.JLabel();
        I_modososcuro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_retroceso.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/btnretroceso.png")); // NOI18N
        btn_retroceso.setBorderPainted(false);
        btn_retroceso.setContentAreaFilled(false);
        btn_retroceso.setMaximumSize(new java.awt.Dimension(84, 84));
        btn_retroceso.setMinimumSize(new java.awt.Dimension(84, 84));
        btn_retroceso.setPreferredSize(new java.awt.Dimension(84, 84));
        btn_retroceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_retrocesoMouseClicked(evt);
            }
        });
        btn_retroceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retrocesoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_retroceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, 40));

        Modo_dificil.setBorderPainted(false);
        Modo_dificil.setContentAreaFilled(false);
        Modo_dificil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Modo_dificilMouseClicked(evt);
            }
        });
        Modo_dificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modo_dificilActionPerformed(evt);
            }
        });
        getContentPane().add(Modo_dificil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 140, 30));

        Modo_facil.setBorderPainted(false);
        Modo_facil.setContentAreaFilled(false);
        Modo_facil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Modo_facilMouseClicked(evt);
            }
        });
        Modo_facil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modo_facilActionPerformed(evt);
            }
        });
        getContentPane().add(Modo_facil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 140, 30));

        Modo_medio.setBorderPainted(false);
        Modo_medio.setContentAreaFilled(false);
        Modo_medio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Modo_medioMouseClicked(evt);
            }
        });
        Modo_medio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modo_medioActionPerformed(evt);
            }
        });
        getContentPane().add(Modo_medio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 140, 30));

        I_modos.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/Modos_1.png")); // NOI18N
        I_modos.setMaximumSize(new java.awt.Dimension(449, 711));
        I_modos.setMinimumSize(new java.awt.Dimension(449, 711));
        I_modos.setPreferredSize(new java.awt.Dimension(449, 711));
        getContentPane().add(I_modos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 401, 760));
        I_modos.getAccessibleContext().setAccessibleDescription("");

        I_modososcuro.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/modosjoscuro.png")); // NOI18N
        I_modososcuro.setMaximumSize(new java.awt.Dimension(449, 711));
        I_modososcuro.setMinimumSize(new java.awt.Dimension(449, 711));
        I_modososcuro.setPreferredSize(new java.awt.Dimension(449, 711));
        getContentPane().add(I_modososcuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 401, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Modo_medioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modo_medioActionPerformed
        opcion = 2;
        // TODO add your handling code here:
    }//GEN-LAST:event_Modo_medioActionPerformed

    private void Modo_facilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modo_facilActionPerformed
        opcion = 1;
// TODO add your handling code here:
    }//GEN-LAST:event_Modo_facilActionPerformed

    private void Modo_dificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modo_dificilActionPerformed
        opcion = 3;
    }//GEN-LAST:event_Modo_dificilActionPerformed

    private void Modo_facilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Modo_facilMouseClicked

        Pantalla_juegoP pjp = new Pantalla_juegoP();
        pjp.setVisible(true);
        pjp.setLocationRelativeTo(null);
        this.dispose();
        
        pjp.iniciar_juego(opcion);
    }//GEN-LAST:event_Modo_facilMouseClicked

    private void Modo_medioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Modo_medioMouseClicked

        Pantalla_juegoP pjp = new Pantalla_juegoP();
        pjp.setVisible(true);
        pjp.setLocationRelativeTo(null);
        this.dispose();
        
        pjp.iniciar_juego(opcion);
    }//GEN-LAST:event_Modo_medioMouseClicked

    private void Modo_dificilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Modo_dificilMouseClicked

        Pantalla_juegoP pjp = new Pantalla_juegoP();
        pjp.setVisible(true);
        pjp.setLocationRelativeTo(null);
        this.dispose();
        
        pjp.iniciar_juego(opcion);
    }//GEN-LAST:event_Modo_dificilMouseClicked

    private void btn_retrocesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_retrocesoMouseClicked
        Pantalla_incio PIN = new Pantalla_incio();
        PIN.setVisible(true);
        PIN.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_retrocesoMouseClicked

    private void btn_retrocesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retrocesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_retrocesoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel I_modos;
    public static javax.swing.JLabel I_modososcuro;
    private javax.swing.JButton Modo_dificil;
    private javax.swing.JButton Modo_facil;
    private javax.swing.JButton Modo_medio;
    private javax.swing.JButton btn_retroceso;
    // End of variables declaration//GEN-END:variables
}
