/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

/**
 *
 * @author rodrigo
 */
import java.awt.Color;
import javax.swing.JOptionPane;
import logica.*;
import logica.Juego;

public class Pantalla_juegoP extends javax.swing.JFrame {

    public Juego juego;
    public Palabra palabra;

    public int intentos_restantes;
    Jugador jugador = Jugador.datos_jugador(null);
    
    /**
     * Creates new form Pantalla_juegoP
     */
    public Pantalla_juegoP() {
        initComponents();
        if (Principal.modo_oscuro) {
            I_juegoposcuro.setVisible(true);
            I_juegop.setVisible(false);
        } else {
            I_juegoposcuro.setVisible(false);
            I_juegop.setVisible(true);
        }

        int dificultad = 1;
        iniciar_juego(dificultad);
    }

    public void iniciar_juego(int dificultad) {

        String nivel = "";
        switch (dificultad) {
            case 1:
                nivel = "facil";
                break;
            case 2:
                nivel = "medio";
                break;
            case 3:
                nivel = "dificil";
                break;
        }
        Gestor_palabras gestor = new Gestor_palabras();
        Palabra palabra1 = gestor.obtenerP_Aleatoria(nivel);
        juego = new Juego(palabra1.obtener(), 9);
        this.palabra = palabra1;
        actualizar_estado();
    }

    private void actualizar_estado() {
        M_intento9.setVisible(false);
        M_intento8.setVisible(false);
        M_intento7.setVisible(false);
        M_intento6.setVisible(false);
        M_intento5.setVisible(false);
        M_intento4.setVisible(false);
        M_intento3.setVisible(false);
        M_intento2.setVisible(false);
        M_intento1.setVisible(false);
        FinJuego.setVisible(false);
        FinJuegoMal.setVisible(false);
        btnfinregreso.setVisible(false);
        pista.setVisible(false);
        pistaT.setVisible(false);

        pistaT.setLineWrap(true);
        pistaT.setWrapStyleWord(true);
        pistaT.setOpaque(false);
        pistaT.setEditable(false);
        pistaT.setBackground(new Color(0, 0, 0, 0));

        scroll.setVisible(false);
        scroll.setOpaque(false);
        scroll.getViewport().setOpaque(false);
        scroll.setBorder(null);

        btnpista.setVisible(true);
        btncpista.setVisible(false);

        String estadoj = juego.estado;
        jLabel2.setText(estadoj);
        intentos_restantes = juego.max_intentos - juego.intento;

        switch (intentos_restantes) {
            case 0:
                M_intento9.setVisible(true);
                break;
            case 1:
                M_intento8.setVisible(true);
                break;
            case 2:
                M_intento7.setVisible(true);
                break;
            case 3:
                M_intento6.setVisible(true);
                break;
            case 4:
                M_intento5.setVisible(true);
                break;
            case 5:
                M_intento4.setVisible(true);
                break;
            case 6:
                M_intento3.setVisible(true);
                break;
            case 7:
                M_intento2.setVisible(true);
                break;
            case 8:
                M_intento1.setVisible(true);
                break;
            default:
                M_incio.setVisible(true);
                break;
        }

        M_incio.setText(juego.obtener_estado());
        M_intento1.setText("Intentos restantes: " + (juego.max_intentos - juego.intento));
        I_juegop.setText("Definición: " + palabra.definicionP());
    }

    private void LetraRecibida(char letra) {

        if (juego.adivinar_letra(letra)) {
            actualizar_estado();
        } else {
            actualizar_estado();
        }

        if (juego.juego_terminado()) {
            if (juego.juego_ganado()) {
                FinJuego.setVisible(true);
                btnfinregreso.setVisible(true);
                jugador.incrementar_puntuacion();
            } else {
                FinJuegoMal.setVisible(true);
                btnfinregreso.setVisible(true);
            }
            JOptionPane.showMessageDialog(this, "");

            this.dispose();
            Pantalla_incio PIN = new Pantalla_incio();
            PIN.setVisible(true);
            PIN.setLocationRelativeTo(null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        pistaT = new javax.swing.JTextArea();
        btnpista = new javax.swing.JButton();
        btncpista = new javax.swing.JButton();
        pista = new javax.swing.JLabel();
        btnfinregreso = new javax.swing.JButton();
        FinJuegoMal = new javax.swing.JLabel();
        FinJuego = new javax.swing.JLabel();
        M_intento9 = new javax.swing.JLabel();
        M_intento8 = new javax.swing.JLabel();
        M_intento7 = new javax.swing.JLabel();
        M_intento6 = new javax.swing.JLabel();
        M_intento5 = new javax.swing.JLabel();
        M_intento4 = new javax.swing.JLabel();
        M_intento3 = new javax.swing.JLabel();
        M_intento2 = new javax.swing.JLabel();
        M_intento1 = new javax.swing.JLabel();
        M_incio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Letra_M = new javax.swing.JButton();
        Letra_N = new javax.swing.JButton();
        Letra_B = new javax.swing.JButton();
        Letra_V = new javax.swing.JButton();
        Letra_C = new javax.swing.JButton();
        Letra_X = new javax.swing.JButton();
        Letra_Z = new javax.swing.JButton();
        Letra_K = new javax.swing.JButton();
        Letra_L = new javax.swing.JButton();
        Letra_Enie = new javax.swing.JButton();
        Letra_J = new javax.swing.JButton();
        Letra_H = new javax.swing.JButton();
        Letra_G = new javax.swing.JButton();
        Letra_F = new javax.swing.JButton();
        Letra_D = new javax.swing.JButton();
        Letra_S = new javax.swing.JButton();
        Letra_A = new javax.swing.JButton();
        Letra_P = new javax.swing.JButton();
        Letra_O = new javax.swing.JButton();
        Letra_I = new javax.swing.JButton();
        Letra_U = new javax.swing.JButton();
        Letra_Y = new javax.swing.JButton();
        Letra_R = new javax.swing.JButton();
        Letra_T = new javax.swing.JButton();
        Letra_E = new javax.swing.JButton();
        Letra_W = new javax.swing.JButton();
        Letra_Q = new javax.swing.JButton();
        I_juegop = new javax.swing.JLabel();
        I_juegoposcuro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scroll.setBackground(new java.awt.Color(254, 207, 109));
        scroll.setBorder(null);
        scroll.setOpaque(false);

        pistaT.setEditable(false);
        pistaT.setBackground(new java.awt.Color(254, 207, 109));
        pistaT.setColumns(20);
        pistaT.setFont(new java.awt.Font("Classic Console", 0, 18)); // NOI18N
        pistaT.setRows(5);
        pistaT.setBorder(null);
        pistaT.setOpaque(false);
        scroll.setViewportView(pistaT);

        getContentPane().add(scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 140, 110));

        btnpista.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/btnpista.png")); // NOI18N
        btnpista.setBorderPainted(false);
        btnpista.setContentAreaFilled(false);
        btnpista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpistaMouseClicked(evt);
            }
        });
        btnpista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpistaActionPerformed(evt);
            }
        });
        getContentPane().add(btnpista, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 190, 40, 60));

        btncpista.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/btnretroceso.png")); // NOI18N
        btncpista.setBorder(null);
        btncpista.setBorderPainted(false);
        btncpista.setContentAreaFilled(false);
        btncpista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncpistaMouseClicked(evt);
            }
        });
        btncpista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncpistaActionPerformed(evt);
            }
        });
        getContentPane().add(btncpista, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 40, 40));

        pista.setBackground(new java.awt.Color(204, 204, 204));
        pista.setFont(new java.awt.Font("Classic Console", 1, 14)); // NOI18N
        pista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pista.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/lpista.png")); // NOI18N
        getContentPane().add(pista, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 270, 270));

        btnfinregreso.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/btnretroceso.png")); // NOI18N
        btnfinregreso.setBorder(null);
        btnfinregreso.setBorderPainted(false);
        btnfinregreso.setContentAreaFilled(false);
        btnfinregreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnfinregresoMouseClicked(evt);
            }
        });
        btnfinregreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfinregresoActionPerformed(evt);
            }
        });
        getContentPane().add(btnfinregreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 40, 40));

        FinJuegoMal.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/finjuegomal.png")); // NOI18N
        getContentPane().add(FinJuegoMal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 350, 350));

        FinJuego.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/finjuego.png")); // NOI18N
        getContentPane().add(FinJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 350, 350));

        M_intento9.setIcon(new javax.swing.ImageIcon("/home/rodrigo/NetBeansProjects/Ahorcado/src/main/java/Imagenes/Mune10.png")); // NOI18N
        getContentPane().add(M_intento9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 270, 270));

        M_intento8.setIcon(new javax.swing.ImageIcon("/home/rodrigo/NetBeansProjects/Ahorcado/src/main/java/Imagenes/Mune9.png")); // NOI18N
        getContentPane().add(M_intento8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 270, 270));

        M_intento7.setIcon(new javax.swing.ImageIcon("/home/rodrigo/NetBeansProjects/Ahorcado/src/main/java/Imagenes/Mune8.png")); // NOI18N
        getContentPane().add(M_intento7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 270, 270));

        M_intento6.setIcon(new javax.swing.ImageIcon("/home/rodrigo/NetBeansProjects/Ahorcado/src/main/java/Imagenes/Mune7.png")); // NOI18N
        getContentPane().add(M_intento6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 270, 270));

        M_intento5.setIcon(new javax.swing.ImageIcon("/home/rodrigo/NetBeansProjects/Ahorcado/src/main/java/Imagenes/Mune6.png")); // NOI18N
        getContentPane().add(M_intento5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 270, 270));

        M_intento4.setIcon(new javax.swing.ImageIcon("/home/rodrigo/NetBeansProjects/Ahorcado/src/main/java/Imagenes/Mune5.png")); // NOI18N
        getContentPane().add(M_intento4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 270, 270));

        M_intento3.setIcon(new javax.swing.ImageIcon("/home/rodrigo/NetBeansProjects/Ahorcado/src/main/java/Imagenes/Mune4.png")); // NOI18N
        getContentPane().add(M_intento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 270, 270));

        M_intento2.setIcon(new javax.swing.ImageIcon("/home/rodrigo/NetBeansProjects/Ahorcado/src/main/java/Imagenes/Mune3.png")); // NOI18N
        getContentPane().add(M_intento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 270, 270));

        M_intento1.setIcon(new javax.swing.ImageIcon("/home/rodrigo/NetBeansProjects/Ahorcado/src/main/java/Imagenes/Mune2.png")); // NOI18N
        getContentPane().add(M_intento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 270, 270));

        M_incio.setIcon(new javax.swing.ImageIcon("/home/rodrigo/NetBeansProjects/Ahorcado/src/main/java/Imagenes/Mune1.png")); // NOI18N
        getContentPane().add(M_incio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 270, 270));

        jLabel2.setFont(new java.awt.Font("Courier", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 370, 50));

        Letra_M.setBorderPainted(false);
        Letra_M.setContentAreaFilled(false);
        Letra_M.setFocusPainted(false);
        Letra_M.setFocusable(false);
        Letra_M.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_MMouseClicked(evt);
            }
        });
        Letra_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_MActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 660, 20, 20));

        Letra_N.setBorderPainted(false);
        Letra_N.setContentAreaFilled(false);
        Letra_N.setFocusPainted(false);
        Letra_N.setFocusable(false);
        Letra_N.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_NMouseClicked(evt);
            }
        });
        Letra_N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_NActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_N, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 660, 30, 20));

        Letra_B.setBorderPainted(false);
        Letra_B.setContentAreaFilled(false);
        Letra_B.setFocusPainted(false);
        Letra_B.setFocusable(false);
        Letra_B.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_BMouseClicked(evt);
            }
        });
        Letra_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_BActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 660, 20, 20));

        Letra_V.setBorderPainted(false);
        Letra_V.setContentAreaFilled(false);
        Letra_V.setFocusPainted(false);
        Letra_V.setFocusable(false);
        Letra_V.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_VMouseClicked(evt);
            }
        });
        Letra_V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_VActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_V, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 20, 20));

        Letra_C.setBorderPainted(false);
        Letra_C.setContentAreaFilled(false);
        Letra_C.setFocusPainted(false);
        Letra_C.setFocusable(false);
        Letra_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_CMouseClicked(evt);
            }
        });
        Letra_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_CActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 660, 20, 20));

        Letra_X.setBorderPainted(false);
        Letra_X.setContentAreaFilled(false);
        Letra_X.setFocusPainted(false);
        Letra_X.setFocusable(false);
        Letra_X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_XMouseClicked(evt);
            }
        });
        Letra_X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_XActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_X, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 660, 30, 20));

        Letra_Z.setBorderPainted(false);
        Letra_Z.setContentAreaFilled(false);
        Letra_Z.setFocusPainted(false);
        Letra_Z.setFocusable(false);
        Letra_Z.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_ZMouseClicked(evt);
            }
        });
        Letra_Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_ZActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_Z, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 20, 20));

        Letra_K.setBorderPainted(false);
        Letra_K.setContentAreaFilled(false);
        Letra_K.setFocusPainted(false);
        Letra_K.setFocusable(false);
        Letra_K.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_KMouseClicked(evt);
            }
        });
        Letra_K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_KActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_K, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 20, 20));

        Letra_L.setBorderPainted(false);
        Letra_L.setContentAreaFilled(false);
        Letra_L.setFocusPainted(false);
        Letra_L.setFocusable(false);
        Letra_L.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_LMouseClicked(evt);
            }
        });
        Letra_L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_LActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_L, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 20, 20));

        Letra_Enie.setBorderPainted(false);
        Letra_Enie.setContentAreaFilled(false);
        Letra_Enie.setFocusPainted(false);
        Letra_Enie.setFocusable(false);
        Letra_Enie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_EnieMouseClicked(evt);
            }
        });
        Letra_Enie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_EnieActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_Enie, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 30, 20));

        Letra_J.setBorderPainted(false);
        Letra_J.setContentAreaFilled(false);
        Letra_J.setFocusPainted(false);
        Letra_J.setFocusable(false);
        Letra_J.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_JMouseClicked(evt);
            }
        });
        Letra_J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_JActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_J, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 30, 20));

        Letra_H.setBorderPainted(false);
        Letra_H.setContentAreaFilled(false);
        Letra_H.setFocusPainted(false);
        Letra_H.setFocusable(false);
        Letra_H.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_HMouseClicked(evt);
            }
        });
        Letra_H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_HActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_H, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, 20, 20));

        Letra_G.setBorderPainted(false);
        Letra_G.setContentAreaFilled(false);
        Letra_G.setFocusPainted(false);
        Letra_G.setFocusable(false);
        Letra_G.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_GMouseClicked(evt);
            }
        });
        Letra_G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_GActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_G, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, 20, 20));

        Letra_F.setBorderPainted(false);
        Letra_F.setContentAreaFilled(false);
        Letra_F.setFocusPainted(false);
        Letra_F.setFocusable(false);
        Letra_F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_FMouseClicked(evt);
            }
        });
        Letra_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_FActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_F, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 620, 30, 20));

        Letra_D.setBorderPainted(false);
        Letra_D.setContentAreaFilled(false);
        Letra_D.setFocusPainted(false);
        Letra_D.setFocusable(false);
        Letra_D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_DMouseClicked(evt);
            }
        });
        Letra_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_DActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, 20, 20));

        Letra_S.setBorderPainted(false);
        Letra_S.setContentAreaFilled(false);
        Letra_S.setFocusPainted(false);
        Letra_S.setFocusable(false);
        Letra_S.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_SMouseClicked(evt);
            }
        });
        Letra_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_SActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_S, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 20, 20));

        Letra_A.setBorderPainted(false);
        Letra_A.setContentAreaFilled(false);
        Letra_A.setFocusPainted(false);
        Letra_A.setFocusable(false);
        Letra_A.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_AMouseClicked(evt);
            }
        });
        Letra_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_AActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_A, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 30, 20));

        Letra_P.setBorderPainted(false);
        Letra_P.setContentAreaFilled(false);
        Letra_P.setFocusPainted(false);
        Letra_P.setFocusable(false);
        Letra_P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_PMouseClicked(evt);
            }
        });
        Letra_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_PActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, 30, 20));

        Letra_O.setBorderPainted(false);
        Letra_O.setContentAreaFilled(false);
        Letra_O.setFocusPainted(false);
        Letra_O.setFocusable(false);
        Letra_O.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_OMouseClicked(evt);
            }
        });
        Letra_O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_OActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_O, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, 20, 20));

        Letra_I.setBorderPainted(false);
        Letra_I.setContentAreaFilled(false);
        Letra_I.setFocusPainted(false);
        Letra_I.setFocusable(false);
        Letra_I.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_IMouseClicked(evt);
            }
        });
        Letra_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_IActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_I, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 10, 20));

        Letra_U.setBorderPainted(false);
        Letra_U.setContentAreaFilled(false);
        Letra_U.setFocusPainted(false);
        Letra_U.setFocusable(false);
        Letra_U.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_UMouseClicked(evt);
            }
        });
        Letra_U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_UActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 30, 20));

        Letra_Y.setBorderPainted(false);
        Letra_Y.setContentAreaFilled(false);
        Letra_Y.setFocusPainted(false);
        Letra_Y.setFocusable(false);
        Letra_Y.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_YMouseClicked(evt);
            }
        });
        Letra_Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_YActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 30, 20));

        Letra_R.setBorderPainted(false);
        Letra_R.setContentAreaFilled(false);
        Letra_R.setFocusPainted(false);
        Letra_R.setFocusable(false);
        Letra_R.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_RMouseClicked(evt);
            }
        });
        Letra_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_RActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_R, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 30, 20));

        Letra_T.setBorderPainted(false);
        Letra_T.setContentAreaFilled(false);
        Letra_T.setFocusPainted(false);
        Letra_T.setFocusable(false);
        Letra_T.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_TMouseClicked(evt);
            }
        });
        Letra_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_TActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_T, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 20, 20));

        Letra_E.setBorderPainted(false);
        Letra_E.setContentAreaFilled(false);
        Letra_E.setFocusPainted(false);
        Letra_E.setFocusable(false);
        Letra_E.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_EMouseClicked(evt);
            }
        });
        Letra_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_EActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_E, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 580, 30, 20));

        Letra_W.setBorderPainted(false);
        Letra_W.setContentAreaFilled(false);
        Letra_W.setFocusPainted(false);
        Letra_W.setFocusable(false);
        Letra_W.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_WMouseClicked(evt);
            }
        });
        Letra_W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_WActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_W, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 30, 20));

        Letra_Q.setBorderPainted(false);
        Letra_Q.setContentAreaFilled(false);
        Letra_Q.setFocusPainted(false);
        Letra_Q.setFocusable(false);
        Letra_Q.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Letra_QMouseClicked(evt);
            }
        });
        Letra_Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Letra_QActionPerformed(evt);
            }
        });
        getContentPane().add(Letra_Q, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 30, 20));

        I_juegop.setIcon(new javax.swing.ImageIcon("/home/rodrigo/NetBeansProjects/Ahorcado/src/main/java/Imagenes/Juego .png")); // NOI18N
        getContentPane().add(I_juegop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 710));

        I_juegoposcuro.setIcon(new javax.swing.ImageIcon("/home/rodrigo/Documentos/POO/Segundo parcial/Ahorcado/Recursos/Imagenes/jposcuro.png")); // NOI18N
        I_juegoposcuro.setText("jLabel1");
        getContentPane().add(I_juegoposcuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Letra_QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_QActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_Letra_QActionPerformed

    private void Letra_WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_WActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_Letra_WActionPerformed

    private void Letra_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_EActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_Letra_EActionPerformed

    private void Letra_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_TActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_Letra_TActionPerformed

    private void Letra_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_RActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_Letra_RActionPerformed

    private void Letra_YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_YActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_YActionPerformed

    private void Letra_UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_UActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_UActionPerformed

    private void Letra_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_IActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_IActionPerformed

    private void Letra_OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_OActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_OActionPerformed

    private void Letra_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_PActionPerformed

    private void Letra_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_AActionPerformed

    private void Letra_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_SActionPerformed

    private void Letra_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_DActionPerformed

    private void Letra_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_FActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_FActionPerformed

    private void Letra_GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_GActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_GActionPerformed

    private void Letra_HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_HActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_HActionPerformed

    private void Letra_JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_JActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_JActionPerformed

    private void Letra_EnieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_EnieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_EnieActionPerformed

    private void Letra_LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_LActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_LActionPerformed

    private void Letra_KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_KActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_KActionPerformed

    private void Letra_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_MActionPerformed

    private void Letra_ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_ZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_ZActionPerformed

    private void Letra_VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_VActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_VActionPerformed

    private void Letra_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_BActionPerformed

    private void Letra_NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_NActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_NActionPerformed

    private void Letra_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_CActionPerformed

    private void Letra_XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Letra_XActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Letra_XActionPerformed

    private void Letra_QMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_QMouseClicked
        LetraRecibida('Q');
        Letra_Q.setOpaque(true);
        Letra_Q.setBackground(new Color(255, 150, 150));
        Letra_Q.setEnabled(false);
    }//GEN-LAST:event_Letra_QMouseClicked

    private void Letra_WMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_WMouseClicked
        LetraRecibida('W');
        Letra_W.setOpaque(true);
        Letra_W.setBackground(new Color(255, 150, 150));
        Letra_W.setEnabled(false);
    }//GEN-LAST:event_Letra_WMouseClicked

    private void Letra_EMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_EMouseClicked
        LetraRecibida('E');
        Letra_E.setOpaque(true);
        Letra_E.setBackground(new Color(255, 150, 150));
        Letra_E.setEnabled(false);
    }//GEN-LAST:event_Letra_EMouseClicked

    private void Letra_RMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_RMouseClicked
        LetraRecibida('R');
        Letra_R.setOpaque(true);
        Letra_R.setBackground(new Color(255, 150, 150));
        Letra_R.setEnabled(false);
    }//GEN-LAST:event_Letra_RMouseClicked

    private void Letra_TMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_TMouseClicked
        LetraRecibida('T');
        Letra_T.setOpaque(true);
        Letra_T.setBackground(new Color(255, 150, 150));
        Letra_T.setEnabled(false);
    }//GEN-LAST:event_Letra_TMouseClicked

    private void Letra_YMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_YMouseClicked
        LetraRecibida('Y');
        Letra_Y.setOpaque(true);
        Letra_Y.setBackground(new Color(255, 150, 150));
        Letra_Y.setEnabled(false);
    }//GEN-LAST:event_Letra_YMouseClicked

    private void Letra_UMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_UMouseClicked
        LetraRecibida('U');
        Letra_U.setOpaque(true);
        Letra_U.setBackground(new Color(255, 150, 150));
        Letra_U.setEnabled(false);
    }//GEN-LAST:event_Letra_UMouseClicked

    private void Letra_IMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_IMouseClicked
        LetraRecibida('I');
        Letra_I.setOpaque(true);
        Letra_I.setBackground(new Color(255, 150, 150));
        Letra_I.setEnabled(false);
    }//GEN-LAST:event_Letra_IMouseClicked

    private void Letra_OMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_OMouseClicked
        LetraRecibida('O');
        Letra_O.setOpaque(true);
        Letra_O.setBackground(new Color(255, 150, 150));
        Letra_O.setEnabled(false);
    }//GEN-LAST:event_Letra_OMouseClicked

    private void Letra_PMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_PMouseClicked
        LetraRecibida('P');
        Letra_P.setOpaque(true);
        Letra_P.setBackground(new Color(255, 150, 150));
        Letra_P.setEnabled(false);

    }//GEN-LAST:event_Letra_PMouseClicked

    private void Letra_AMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_AMouseClicked
        LetraRecibida('A');
        Letra_A.setOpaque(true);
        Letra_A.setBackground(new Color(255, 150, 150));
        Letra_A.setEnabled(false);
    }//GEN-LAST:event_Letra_AMouseClicked

    private void Letra_SMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_SMouseClicked
        LetraRecibida('S');
        Letra_S.setOpaque(true);
        Letra_S.setBackground(new Color(255, 150, 150));
        Letra_S.setEnabled(false);
    }//GEN-LAST:event_Letra_SMouseClicked

    private void Letra_DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_DMouseClicked
        LetraRecibida('D');
        Letra_D.setOpaque(true);
        Letra_D.setBackground(new Color(255, 150, 150));
        Letra_D.setEnabled(false);
    }//GEN-LAST:event_Letra_DMouseClicked

    private void Letra_FMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_FMouseClicked
        LetraRecibida('F');
        Letra_F.setOpaque(true);
        Letra_F.setBackground(new Color(255, 150, 150));
        Letra_F.setEnabled(false);
    }//GEN-LAST:event_Letra_FMouseClicked

    private void Letra_GMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_GMouseClicked
        LetraRecibida('G');
        Letra_G.setOpaque(true);
        Letra_G.setBackground(new Color(255, 150, 150));
        Letra_G.setEnabled(false);
    }//GEN-LAST:event_Letra_GMouseClicked

    private void Letra_HMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_HMouseClicked
        LetraRecibida('H');
        Letra_H.setOpaque(true);
        Letra_H.setBackground(new Color(255, 150, 150));
        Letra_H.setEnabled(false);
    }//GEN-LAST:event_Letra_HMouseClicked

    private void Letra_JMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_JMouseClicked
        LetraRecibida('J');
        Letra_J.setOpaque(true);
        Letra_J.setBackground(new Color(255, 150, 150));
        Letra_J.setEnabled(false);
    }//GEN-LAST:event_Letra_JMouseClicked

    private void Letra_KMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_KMouseClicked
        LetraRecibida('K');
        Letra_K.setOpaque(true);
        Letra_K.setBackground(new Color(255, 150, 150));
        Letra_K.setEnabled(false);
    }//GEN-LAST:event_Letra_KMouseClicked

    private void Letra_LMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_LMouseClicked
        LetraRecibida('L');
        Letra_L.setOpaque(true);
        Letra_L.setBackground(new Color(255, 150, 150));
        Letra_L.setEnabled(false);
    }//GEN-LAST:event_Letra_LMouseClicked

    private void Letra_EnieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_EnieMouseClicked
        LetraRecibida('Ñ');
        Letra_Enie.setOpaque(true);
        Letra_Enie.setBackground(new Color(255, 150, 150));
        Letra_Enie.setEnabled(false);
    }//GEN-LAST:event_Letra_EnieMouseClicked

    private void Letra_ZMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_ZMouseClicked
        LetraRecibida('Z');
        Letra_Z.setOpaque(true);
        Letra_Z.setBackground(new Color(255, 150, 150));
        Letra_Z.setEnabled(false);
    }//GEN-LAST:event_Letra_ZMouseClicked

    private void Letra_XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_XMouseClicked
        LetraRecibida('X');
        Letra_X.setOpaque(true);
        Letra_X.setBackground(new Color(255, 150, 150));
        Letra_X.setEnabled(false);
    }//GEN-LAST:event_Letra_XMouseClicked

    private void Letra_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_CMouseClicked
        LetraRecibida('C');
        Letra_C.setOpaque(true);
        Letra_C.setBackground(new Color(255, 150, 150));
        Letra_C.setEnabled(false);
    }//GEN-LAST:event_Letra_CMouseClicked

    private void Letra_VMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_VMouseClicked
        LetraRecibida('V');
        Letra_V.setOpaque(true);
        Letra_V.setBackground(new Color(255, 150, 150));
        Letra_V.setEnabled(false);
    }//GEN-LAST:event_Letra_VMouseClicked

    private void Letra_BMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_BMouseClicked
        LetraRecibida('B');
        Letra_B.setOpaque(true);
        Letra_B.setBackground(new Color(255, 150, 150));
        Letra_B.setEnabled(false);
    }//GEN-LAST:event_Letra_BMouseClicked

    private void Letra_NMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_NMouseClicked
        LetraRecibida('N');
        Letra_N.setOpaque(true);
        Letra_N.setBackground(new Color(255, 150, 150));
        Letra_N.setEnabled(false);
    }//GEN-LAST:event_Letra_NMouseClicked

    private void Letra_MMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Letra_MMouseClicked
        LetraRecibida('M');
        Letra_M.setOpaque(true);
        Letra_M.setBackground(new Color(255, 150, 150));
        Letra_M.setEnabled(false);
    }//GEN-LAST:event_Letra_MMouseClicked

    private void btnfinregresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfinregresoMouseClicked
        Pantalla_incio PIN = new Pantalla_incio();
        PIN.setVisible(true);
        PIN.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnfinregresoMouseClicked

    private void btnfinregresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfinregresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnfinregresoActionPerformed

    private void btnpistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpistaActionPerformed

    private void btnpistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpistaMouseClicked
        pistaT.setText("Pista: " + palabra.definicionP());
        pistaT.setVisible(true);
        pista.setVisible(true);
        scroll.setVisible(true);
        btncpista.setVisible(true);
    }//GEN-LAST:event_btnpistaMouseClicked

    private void btncpistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncpistaMouseClicked
        pistaT.setVisible(false);
        pista.setVisible(false);
        scroll.setVisible(false);
        btncpista.setVisible(false);
    }//GEN-LAST:event_btncpistaMouseClicked

    private void btncpistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncpistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncpistaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FinJuego;
    private javax.swing.JLabel FinJuegoMal;
    private javax.swing.JLabel I_juegop;
    private javax.swing.JLabel I_juegoposcuro;
    private javax.swing.JButton Letra_A;
    private javax.swing.JButton Letra_B;
    private javax.swing.JButton Letra_C;
    private javax.swing.JButton Letra_D;
    private javax.swing.JButton Letra_E;
    private javax.swing.JButton Letra_Enie;
    private javax.swing.JButton Letra_F;
    private javax.swing.JButton Letra_G;
    private javax.swing.JButton Letra_H;
    private javax.swing.JButton Letra_I;
    private javax.swing.JButton Letra_J;
    private javax.swing.JButton Letra_K;
    private javax.swing.JButton Letra_L;
    private javax.swing.JButton Letra_M;
    private javax.swing.JButton Letra_N;
    private javax.swing.JButton Letra_O;
    private javax.swing.JButton Letra_P;
    private javax.swing.JButton Letra_Q;
    private javax.swing.JButton Letra_R;
    private javax.swing.JButton Letra_S;
    private javax.swing.JButton Letra_T;
    private javax.swing.JButton Letra_U;
    private javax.swing.JButton Letra_V;
    private javax.swing.JButton Letra_W;
    private javax.swing.JButton Letra_X;
    private javax.swing.JButton Letra_Y;
    private javax.swing.JButton Letra_Z;
    private javax.swing.JLabel M_incio;
    private javax.swing.JLabel M_intento1;
    private javax.swing.JLabel M_intento2;
    private javax.swing.JLabel M_intento3;
    private javax.swing.JLabel M_intento4;
    private javax.swing.JLabel M_intento5;
    private javax.swing.JLabel M_intento6;
    private javax.swing.JLabel M_intento7;
    private javax.swing.JLabel M_intento8;
    private javax.swing.JLabel M_intento9;
    private javax.swing.JButton btncpista;
    private javax.swing.JButton btnfinregreso;
    private javax.swing.JButton btnpista;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel pista;
    private javax.swing.JTextArea pistaT;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
